"""
GOLDEN REGRESSION TESTS — POISSON_V1

*** DO NOT EDIT THE EXPECTED VALUES IN THIS FILE. ***

Every expected value below was generated by executing the CURRENT `poisson.py`
implementation (commit be67223 lineage) on 2026-08-07. None was hand-computed,
rounded or "corrected".

Purpose: if a future refactor changes POISSON_V1 mathematics in any way, these
tests fail immediately. That is their only job.

If a test here fails, the correct response is to ask "what changed in the model?",
NOT to update the expected value. A value may only be changed as part of a
deliberate, documented model version bump (e.g. introducing POISSON_V2), and the
old values should be preserved for the historical baseline.

Coverage spans: balanced teams, strong home attack, strong away attack, weak
attack, strong defence, high-scoring environment, low-scoring environment, a
heavy mismatch, the legacy zero-value cases, minimal intensity, and the ESPN
hardcoded 1.35 league-average fallback that production actually uses.
"""

from dataclasses import dataclass

import pytest

from poisson import calculate_gg_probability

# Relative tolerance for float comparison. Tight enough to catch any real change
# in the formula, loose enough to survive platform-level float representation
# differences. Deliberately not a string comparison.
REL_TOL = 1e-12


@dataclass(frozen=True)
class GoldenCase:
    name: str
    league_avg_goals: float
    home_goals_scored_home: float
    home_goals_conceded_home: float
    away_goals_scored_away: float
    away_goals_conceded_away: float
    expected_lambda_home: float
    expected_lambda_away: float
    expected_gg_probability: float


GOLDEN_CASES = [
    GoldenCase(
        name="balanced_average_teams",
        league_avg_goals=1.35,
        home_goals_scored_home=1.5,
        home_goals_conceded_home=1.2,
        away_goals_scored_away=1.3,
        away_goals_conceded_away=1.4,
        expected_lambda_home=1.5555555555555551,
        expected_lambda_away=1.1555555555555554,
        expected_gg_probability=0.5405082766461281,
    ),
    GoldenCase(
        name="strong_home_attack",
        league_avg_goals=1.35,
        home_goals_scored_home=2.4,
        home_goals_conceded_home=0.8,
        away_goals_scored_away=1.0,
        away_goals_conceded_away=1.6,
        expected_lambda_home=2.844444444444444,
        expected_lambda_away=0.5925925925925926,
        expected_gg_probability=0.42110125888587685,
    ),
    GoldenCase(
        name="strong_away_attack",
        league_avg_goals=1.35,
        home_goals_scored_home=1.0,
        home_goals_conceded_home=1.6,
        away_goals_scored_away=2.3,
        away_goals_conceded_away=0.9,
        expected_lambda_home=0.6666666666666666,
        expected_lambda_away=2.7259259259259254,
        expected_gg_probability=0.4547187383115904,
    ),
    GoldenCase(
        name="weak_attack_both_sides",
        league_avg_goals=1.35,
        home_goals_scored_home=0.6,
        home_goals_conceded_home=1.1,
        away_goals_scored_away=0.5,
        away_goals_conceded_away=1.2,
        expected_lambda_home=0.5333333333333333,
        expected_lambda_away=0.40740740740740744,
        expected_gg_probability=0.13831931187577634,
    ),
    GoldenCase(
        name="strong_defence_both_sides",
        league_avg_goals=1.35,
        home_goals_scored_home=1.4,
        home_goals_conceded_home=0.4,
        away_goals_scored_away=1.3,
        away_goals_conceded_away=0.45,
        expected_lambda_home=0.4666666666666666,
        expected_lambda_away=0.3851851851851852,
        expected_gg_probability=0.11921043147474679,
    ),
    GoldenCase(
        name="high_scoring_environment",
        league_avg_goals=1.8,
        home_goals_scored_home=2.1,
        home_goals_conceded_home=1.9,
        away_goals_scored_away=2.0,
        away_goals_conceded_away=1.85,
        expected_lambda_home=2.158333333333333,
        expected_lambda_away=2.111111111111111,
        expected_gg_probability=0.7773687307404705,
    ),
    GoldenCase(
        name="low_scoring_environment",
        league_avg_goals=0.95,
        home_goals_scored_home=0.9,
        home_goals_conceded_home=0.85,
        away_goals_scored_away=0.8,
        away_goals_conceded_away=0.95,
        expected_lambda_home=0.9,
        expected_lambda_away=0.7157894736842106,
        expected_gg_probability=0.30335799380822953,
    ),
    GoldenCase(
        name="heavy_favourite_vs_minnow",
        league_avg_goals=1.35,
        home_goals_scored_home=3.1,
        home_goals_conceded_home=0.5,
        away_goals_scored_away=0.4,
        away_goals_conceded_away=2.8,
        expected_lambda_home=6.429629629629629,
        expected_lambda_away=0.14814814814814814,
        expected_gg_probability=0.13747453185134295,
    ),
    # Legacy zero-value cases. These exist BECAUSE of GG-001: a missing statistic
    # arrives as 0.0 and is accepted as real data. Frozen so that when Epic 1B
    # changes missing-data handling, the change is visible here.
    GoldenCase(
        name="zero_home_scoring_legacy",
        league_avg_goals=1.35,
        home_goals_scored_home=0.0,
        home_goals_conceded_home=1.2,
        away_goals_scored_away=1.3,
        away_goals_conceded_away=1.4,
        expected_lambda_home=0.0,
        expected_lambda_away=1.1555555555555554,
        expected_gg_probability=0.0,
    ),
    GoldenCase(
        name="zero_conceded_both_legacy",
        league_avg_goals=1.35,
        home_goals_scored_home=1.5,
        home_goals_conceded_home=0.0,
        away_goals_scored_away=1.3,
        away_goals_conceded_away=0.0,
        expected_lambda_home=0.0,
        expected_lambda_away=0.0,
        expected_gg_probability=0.0,
    ),
    GoldenCase(
        name="minimal_positive_intensity",
        league_avg_goals=1.35,
        home_goals_scored_home=0.01,
        home_goals_conceded_home=0.01,
        away_goals_scored_away=0.01,
        away_goals_conceded_away=0.01,
        expected_lambda_home=7.407407407407407e-05,
        expected_lambda_away=7.407407407407407e-05,
        expected_gg_probability=5.486562025390666e-09,
    ),
    # The league average production actually uses: espn.get_league_avg_goals()
    # always falls through to the hardcoded 1.35 (GG-003).
    GoldenCase(
        name="espn_fallback_league_avg_1_35",
        league_avg_goals=1.35,
        home_goals_scored_home=1.75,
        home_goals_conceded_home=1.05,
        away_goals_scored_away=1.45,
        away_goals_conceded_away=1.25,
        expected_lambda_home=1.6203703703703702,
        expected_lambda_away=1.1277777777777778,
        expected_gg_probability=0.5424690326701521,
    ),
]

CASE_IDS = [case.name for case in GOLDEN_CASES]


@pytest.mark.golden
@pytest.mark.parametrize("case", GOLDEN_CASES, ids=CASE_IDS)
def test_lambda_home_unchanged(case: GoldenCase):
    result = calculate_gg_probability(
        case.league_avg_goals,
        case.home_goals_scored_home,
        case.home_goals_conceded_home,
        case.away_goals_scored_away,
        case.away_goals_conceded_away,
    )
    assert result is not None
    assert result["lambda_home"] == pytest.approx(
        case.expected_lambda_home, rel=REL_TOL, abs=1e-15
    ), f"POISSON_V1 lambda_home drifted for {case.name}"


@pytest.mark.golden
@pytest.mark.parametrize("case", GOLDEN_CASES, ids=CASE_IDS)
def test_lambda_away_unchanged(case: GoldenCase):
    result = calculate_gg_probability(
        case.league_avg_goals,
        case.home_goals_scored_home,
        case.home_goals_conceded_home,
        case.away_goals_scored_away,
        case.away_goals_conceded_away,
    )
    assert result is not None
    assert result["lambda_away"] == pytest.approx(
        case.expected_lambda_away, rel=REL_TOL, abs=1e-15
    ), f"POISSON_V1 lambda_away drifted for {case.name}"


@pytest.mark.golden
@pytest.mark.parametrize("case", GOLDEN_CASES, ids=CASE_IDS)
def test_gg_probability_unchanged(case: GoldenCase):
    result = calculate_gg_probability(
        case.league_avg_goals,
        case.home_goals_scored_home,
        case.home_goals_conceded_home,
        case.away_goals_scored_away,
        case.away_goals_conceded_away,
    )
    assert result is not None
    assert result["gg_probability"] == pytest.approx(
        case.expected_gg_probability, rel=REL_TOL, abs=1e-15
    ), f"POISSON_V1 gg_probability drifted for {case.name}"


@pytest.mark.golden
def test_golden_suite_covers_required_scenarios():
    """The Epic 1A brief requires each of these scenario families."""
    names = set(CASE_IDS)
    required = {
        "balanced_average_teams",
        "strong_home_attack",
        "strong_away_attack",
        "weak_attack_both_sides",
        "strong_defence_both_sides",
        "high_scoring_environment",
        "low_scoring_environment",
    }
    assert required <= names
    assert len(GOLDEN_CASES) == 12


@pytest.mark.golden
def test_golden_cases_are_stable_across_repeated_evaluation():
    """A golden suite is only meaningful if the model is deterministic."""
    for case in GOLDEN_CASES:
        args = (
            case.league_avg_goals,
            case.home_goals_scored_home,
            case.home_goals_conceded_home,
            case.away_goals_scored_away,
            case.away_goals_conceded_away,
        )
        first = calculate_gg_probability(*args)
        for _ in range(5):
            assert calculate_gg_probability(*args) == first
